server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.68.0.117:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=true&&serverTimezone=GMT%2B8
    username: root
    password: password

  redis:
    host: 10.68.0.117

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/oms/**/*.xml

